### PR TITLE
Fix build

### PR DESCRIPTION
**Pull request by Falci**
No more ghost commits!

### CODE REVIEW

**Comment by Falci** [comment]
✅  Build [here](https://github.com/Falci/bob-wallet/runs/2526054024).

**Comment by pinheadmz** [comment]
@Falci do you know what `libudev-dev` is or what it does or why we suddenly need it? Could it indicate a different issue with the CI? For example the wrong base image or nodejs version? Do we need to add this to the dependencies in the README for everyone to build from now on? If not, why does this only affect the CI? 

This is the stuff I wanna know before making this change, even though its not going into the production app.

**Comment by Falci** [comment]
Sure.

You added a dependency of [handshake-org/hsd-ledger](https://github.com/handshake-org/hsd-ledger), which depends on [nodech/busb](https://github.com/nodech/busb), which list `libudev-dev` as [dependencies](https://github.com/nodech/busb#debianubuntu).

**Comment by pinheadmz** [comment]
Cherry picking your commit, thanks!
Can't merge the PR because I already rebase and so we have nasty conflicts.

**Comment by pinheadmz** [comment]
https://github.com/kyokan/bob-wallet/pull/344/commits/8eb03b296bb59f98e38c22495b6fa54451788ae8

**Pull request closed without merging**
